jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: ls
    features:
      - type: free-disk-space
        required-space: 4194304 KB
        fail-build: true
    allow-reuse: false
